"""Management of the shell profile lines that point clients at the server."""

from __future__ import annotations

from pathlib import Path

from llm.core.files import write_atomic


def _ensure_line_in_file(path: Path, line: str) -> bool:
    """Ensure *line* is present in *path*. Creates the file if needed.

    Returns True if the line was added, False if already present.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        content = path.read_text()
        if line in content:
            return False
    with path.open("a") as f:
        f.write(f"\n{line}\n")
    return True


def configure_shell_env_host(
    base_url: str,
    api_key: str,
    cert_path: str,
) -> list[str]:
    """Configure shell env vars on the host for bash and fish.

    Writes to dedicated config files:
    - ~/.config/local-llm/env (sourced from ~/.bashrc)
    - ~/.config/fish/conf.d/local-llm.fish

    Returns a list of actions taken.
    """
    home = Path.home()
    actions: list[str] = []

    # ── Bash: dedicated env file sourced from bashrc ──────────────────────
    env_dir = home / ".config" / "local-llm"
    env_file = env_dir / "env"
    env_dir.mkdir(parents=True, exist_ok=True)

    env_content = (
        "# Generated by local-llm - do not edit manually\n"
        f'export PATH="$HOME/.local/bin:$PATH"\n'
        f'export OPENAI_BASE_URL="{base_url}"\n'
        f'export OPENAI_API_KEY="{api_key}"\n'
        f'export NODE_EXTRA_CA_CERTS="{cert_path}"\n'
    )
    # 0600: the env file exports OPENAI_API_KEY.
    write_atomic(env_file, env_content, mode=0o600)
    actions.append(f"Wrote {env_file}")

    # Source from ~/.bashrc if not already present
    source_line = f'[ -f "{env_file}" ] && source "{env_file}"'
    bashrc = home / ".bashrc"
    if _ensure_line_in_file(bashrc, source_line):
        actions.append(f"Added source line to {bashrc}")

    # ── Fish: conf.d snippet ──────────────────────────────────────────────
    fish_conf = home / ".config" / "fish" / "conf.d" / "local-llm.fish"
    fish_content = (
        "# Generated by local-llm - do not edit manually\n"
        f'set -gx PATH "$HOME/.local/bin" $PATH\n'
        f'set -gx OPENAI_BASE_URL "{base_url}"\n'
        f'set -gx OPENAI_API_KEY "{api_key}"\n'
        f'set -gx NODE_EXTRA_CA_CERTS "{cert_path}"\n'
    )
    fish_conf.parent.mkdir(parents=True, exist_ok=True)
    write_atomic(fish_conf, fish_content, mode=0o600)
    actions.append(f"Wrote {fish_conf}")

    return actions
